[workspace]
resolver = "2"
default-members = ["crates/*"]
members = ["crates/*", "contracts/*"]

[workspace.package]
repository = "https://github.com/theahaco/scaffold-stellar"

[workspace.dependencies]
stellar-scaffold-macro = { path = "crates/stellar-scaffold-macro" }
stellar-registry = { path = "crates/stellar-registry" }

stellar-cli = { version = "23.1.3", package = "soroban-cli" }
soroban-rpc = { package = "stellar-rpc-client", version = "23.0.0" }
soroban-spec-tools = "23.0.0"

soroban-sdk = { git = "https://github.com/theahaco/rs-soroban-sdk", rev = "367e4efc2462c841b046aeac0dda8fcee05b790f" }
admin-sep = { git = "https://github.com/AhaLabs/admin-sep", rev = "b695582c31ee14602bea9f1cc1a68357ffe1d0a9" }
stellar-xdr = "23.0.0"
stellar-strkey = "0.0.13"

cargo_metadata = "0.18.1"
thiserror = "1.0.38"
sha2 = "0.10.8"

[profile.contracts]
inherits = "release"
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = true
panic = "abort"
codegen-units = 1
lto = true

[workspace.lints.clippy]
