[package]
name = "registry"
description = "A crate for managing and deploying smart contracts on the Soroban blockchain."
version = "0.1.1"
authors = ["Aha Labs <hello@theaha.co>"]
license = "Apache-2.0"
rust-version = "1.69"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk = { git = "https://github.com/AhaLabs/rs-soroban-sdk", rev = "5a99659f1483c926ff87ea45f8823b8c00dc4cbd" }
admin-sep = { git = "https://github.com/AhaLabs/admin-sep", rev = "4f1e3f942c7815d3e7fb4e379132ef8d19dfc54c" }
semver = { version = "1.0.26", default-features = false }

[dev-dependencies]
soroban-sdk = { git = "https://github.com/AhaLabs/rs-soroban-sdk", rev = "5a99659f1483c926ff87ea45f8823b8c00dc4cbd", features = ["testutils"] }
stellar-registry = { workspace = true }
assert_matches = "1.5.0"

[package.metadata.loam]
contract = true

[package.metadata.stellar]
cargo_inherit = true
homepage = "theaha.co"
repository = "https://github.com/theahaco/scaffold-stellar"
